# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  auth_idserver:
    build:
      context: "C:\\Users\\achil\\Projects\\CRM"
      dockerfile: "./Auth/src/Auth.IdServer/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Auth.IdServer.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "auth.idserver:dev"
    ports:
    - "127.0.0.1:57072:57100"
    - "127.0.0.1:57272:57300"
    volumes:
    - "C:\\Users\\achil\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\achil\\Projects\\CRM\\Auth\\src\\Auth.IdServer:/app:rw"
    - "C:\\Users\\achil\\Projects\\CRM\\Auth:/src:rw"
    - "C:\\Users\\achil\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1.5\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.3.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\achil\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_11_24_15_40_52:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  auth_idserverwebsite:
    build:
      context: "C:\\Users\\achil\\Projects\\CRM"
      dockerfile: "./Auth/src/Auth.IdServerWebsite/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Auth.IdServerWebsite.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "auth.idserverwebsite:dev"
    ports:
    - "127.0.0.1:57073:57100"
    - "127.0.0.1:57273:57300"
    volumes:
    - "C:\\Users\\achil\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\achil\\Projects\\CRM\\Auth\\src\\Auth.IdServerWebsite:/app:rw"
    - "C:\\Users\\achil\\Projects\\CRM\\Auth:/src:rw"
    - "C:\\Users\\achil\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1.5\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.3.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\achil\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_11_24_15_40_52:/var/opt/rider-debugger:rw"
    working_dir: "/app"
